---
kind: pipeline
type: docker
name: default

steps:
  # - name: lint
  #   image: 0xb1b1/drone-linter
  # - name: docker-build
  #   image: plugins/docker
  #   pull: never
  #   settings:
  #     dockerfile: backend/Dockerfile
  #     context: src
  #     repo: 0xb1b1/decisive-stump-backend
  #     tags: dev
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  - name: test
    image: debian:latest
    commands:
      - ps
